AllCops:
  TargetRailsVersion: 5.2
Rails:
  Enabled: true
Metrics/BlockLength:
  Max: 80
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 30
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/WordArray:
  EnforcedStyle: brackets
Style/SymbolArray:
  EnforcedStyle: brackets
