development:
  adapter: postgresql
  database: maps_development
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  database: maps_test
  host: localhost
  port: 5432

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

cucumber:
  <<: *test
